#!/usr/bin/env python2.6
# -*- coding: utf-8 -*-

from xamai.Upload import Upload
from xamai.Login import Login
from xamai.Gui import Gui

l = Login()

if l.isActive():
    app = Upload()
    app.sync()
else:
    import sys

    from PyQt4.QtGui import QApplication

    import xamai.Ui as gui
    from xamai.QtWebKit import QtWebkit

    app = QApplication(sys.argv)

    data = {
        "css": gui.loadStyles(),
        "alert": "",
        "app-version": "v" + str(const.VERSION)
    }

    web = QtWebkit(app, gui.readHTML("login.html", data))
    web.show()
    web.raise_()

    sys.exit(app.exec_())