#!/usr/bin/env python
# -*- coding: utf-8 -*-
from xamai.Scanda import Scanda
from xamai.Login import Login
from xamai.Ui import GUI

l = Login()

if l.isActive():
    app = Scanda()
    app.main()
else:
    app = GUI()
    app.login()