#!/usr/bin/env python2.6
# -*- coding: utf-8 -*-
import os
import sys
from PyQt4 import QtGui

import xamai.Constants as const
from xamai.Login import Login
from xamai.Tray import DBProtectorTrayIcon

l = Login()

if l.isActive():
    app = QtGui.QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)
    w = QtGui.QWidget()
    icon_file = os.path.join(const.LOCATION, const.ICONO)
    trayIcon = DBProtectorTrayIcon(QtGui.QIcon(icon_file), w)

    trayIcon.show()
    sys.exit(app.exec_())
else:
    import sys

    from PyQt4.QtGui import QApplication

    import xamai.Ui as gui
    from xamai.QtWebKit import QtWebkit

    app = QApplication(sys.argv)

    data = {
        "js": gui.loadJS(),
        "css": gui.loadStyles(),
        "alert": "",
        "app-version": "v" + str(const.VERSION)
    }

    web = QtWebkit(app, gui.readHTML("login.html", data))
    web.show()
    web.raise_()

    sys.exit(app.exec_())