#!/usr/bin/env python
# -*- coding: utf-8 -*-
from scanda.Scanda import Scanda
from scanda.Login import Login
from scanda.Ui import GUI

l = Login()

if l.isActive():
    app = Scanda()
    app.main()
else:
    app = GUI()
    app.login()