#! /bin/bash
# Si el archivo de configuracion fue respaldado, lo restaura
if [[ -f /tmp/configuration.json ]]; then
    cp /tmp/configuration.json /usr/local/lib64/python2.6/site-packages/xamai/settings/configuration.json
fi

sudo chmod -R 777 /usr/local/lib64/python2.6/site-packages/xamai/settings/
# Varia de acuerdo a la version de GNOME y la distribucion linux
echo '[Desktop Entry]
Categories=Development;Database;
Encoding=UTF-8
Name=DBProtector (Install)
GenericName=dbprotector
Comment=DBProtector
TryExec=dbprotector_pre-install
Exec=dbprotector_pre-install
Icon=/usr/local/lib64/python2.6/site-packages/xamai/img/DB_Protector_32X32.png
Terminal=true
StartupNotify=true
Type=Application' >> /usr/share/applications/dbprotector.desktop
