#! /bin/bash
# Python installer
#zypper addrepo --check --refresh --name 'openSUSE-Leap-42.1-Update' http://download.opensuse.org/update/leap/42.1/oss/ repo-update
zypper addrepo --check --refresh --name 'openSUSE-Leap-42.1' http://download.opensuse.org/distribution/leap/42.1/repo/oss/ repo-dist
zypper in -y libopenssl-devel zlib-devel ncurses-devel